# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# .github/dependabot.yml
version: 2
updates:
  # 1) Keep GitHub Actions up to date (all workflows under .github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"  # covers .github/workflows under the repo root
    schedule:
      interval: "weekly"      # run weekly
      day: "monday"           # every Monday
      time: "04:00"           # at 04:00 local time
      timezone: "Europe/Sofia"
    target-branch: "main"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"         # e.g., "chore: bump actions/*"
      include: "scope"
    # Create a single PR that includes ALL action updates (major + minor + patch)
    groups:
      all-actions:
        patterns: ["*"]
        update-types: ["major", "minor", "patch"]

  # 2) Keep NuGet packages up to date across all .csproj/.sln found in this repo
  - package-ecosystem: "nuget"
    directory: "/"  # Dependabot will discover projects recursively
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Sofia"
    target-branch: "main"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"         # e.g., "chore: bump MySqlConnector"
      include: "scope"
    versioning-strategy: "auto"  # allow major/minor/patch according to semver info
    # Create a single PR that includes ALL NuGet updates (major + minor + patch)
    groups:
      all-nuget:
        patterns: ["*"]
        update-types: ["major", "minor", "patch"]

