# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# .github/dependabot.yml
version: 2

# Define a single group spanning multiple ecosystems.
multi-ecosystem-groups:
  surfstack:                      # any name you like
    # The group has its own schedule; individual updates inherit it.
    schedule:
      interval: "weekly"          # weekly check
      day: "monday"               # every Monday
      time: "04:00"               # at 04:00 local time
      timezone: "Europe/Sofia"

updates:
  # Keep GitHub Actions up to date (all workflows).
  - package-ecosystem: "github-actions"
    directory: "/"                # covers .github/workflows
    target-branch: "main"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Include all action dependencies in the multi-ecosystem PR.
    patterns: ["*"]
    multi-ecosystem-group: "surfstack"

  # Keep all NuGet packages up to date across the repo.
  - package-ecosystem: "nuget"
    directory: "/"                # Dependabot discovers projects recursively
    target-branch: "main"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Include all NuGet dependencies in the same multi-ecosystem PR.
    patterns: ["*"]
    multi-ecosystem-group: "surfstack"
