name: Build API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout API repo
        uses: actions/checkout@v4

      - name: Checkout Shared repo
        uses: actions/checkout@v4
        with:
          repository: tslashd/SurfTimer.Shared
          path: ../SurfTimer.Shared   # ще се появи една папка нагоре спрямо SurfTimer.Api

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore SurfTimer.Api.sln

      - name: Build
        run: dotnet build SurfTimer.Api.sln -c Release --no-restore

      - name: Publish
        run: dotnet publish SurfTimer.Api/SurfTimer.Api.csproj -c Release -o out
