name: Build SurfTimer.Api Clean

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SurfTimer.Api
        uses: actions/checkout@v3

      - name: Checkout SurfTimer.Shared
        uses: actions/checkout@v3
        with:
          repository: tslashd/SurfTimer.Shared
          path: SurfTimer.Shared

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Add project reference dynamically
        run: |
          dotnet sln add SurfTimer.Shared/SurfTimer.Shared.csproj
          dotnet add SurfTimer.Api/SurfTimer.Api.csproj reference SurfTimer.Shared/SurfTimer.Shared.csproj

      - name: Restore dependencies
        run: dotnet restore SurfTimer.Api/SurfTimer.Api.csproj

      - name: Build API
        run: dotnet build SurfTimer.Api/SurfTimer.Api.csproj -c Release
